export const ActionTypes = {
    SHOW_SINGLE_PRODUCT: 'SHOW_SINGLE_PRODUCT',
    BOOKING_ROOM: 'BOOKING_ROOM',
    FILLTER_ROOM: 'FILLTER_ROOM',
    SHOW_LIST_ROOM: 'SHOW_LIST_ROOM',
    // ADMIN
    ADMIN_NEW_ROOM: 'ADMIN_NEW_ROOM',
    ADMIN_EDIT_ROOM: 'ADMIN_EDIT_ROOM',
    ADMIN_DEL_ROOM: 'ADMIN_DEL_ROOM',
    ADMIN_NEW_CATEGORY: 'ADMIN_NEW_CATEGORY',
    ADMIN_EDIT_CATEGORY: 'ADMIN_EDIT_CATEGORY',
    ADMIN_DEL_CATEGORY: 'ADMIN_DEL_CATEGORY',
    ADMIN_NEW_USER: 'ADMIN_NEW_USER',
    ADMIN_EDIT_USER: 'ADMIN_EDIT_USER',
    ADMIN_DEL_USER: 'ADMIN_DEL_USER',
  }